name: harry_potter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  floor: ^1.4.2
  http: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.4.6
  floor_generator: 1.4.2

flutter:
  uses-material-design: true
